
var _scopes = []

var _scopes_analytics = [
	TWITCH_SCOPE_ANALYTICS_READ_EXTENSIONS,
	TWITCH_SCOPE_ANALYTICS_READ_GAMES,
]

var _scopes_bits = [
	TWITCH_SCOPE_BITS_READ
]

var _scopes_channel = [
	TWITCH_SCOPE_CHANNEL_BOT,
	TWITCH_SCOPE_CHANNEL_EDIT_COMMERCIAL,
	TWITCH_SCOPE_CHANNEL_MANAGE_ADS,
	TWITCH_SCOPE_CHANNEL_MANAGE_BROADCAST,
	TWITCH_SCOPE_CHANNEL_MANAGE_EXTENSIONS,
	TWITCH_SCOPE_CHANNEL_MANAGE_POLLS,
	TWITCH_SCOPE_CHANNEL_MANAGE_PREDICTIONS,
	TWITCH_SCOPE_CHANNEL_MANAGE_RAIDS,
	TWITCH_SCOPE_CHANNEL_MANAGE_REDEMPTIONS,
	TWITCH_SCOPE_CHANNEL_MANAGE_SCHEDULE,
	TWITCH_SCOPE_CHANNEL_MANAGE_VIDEOS,
	TWITCH_SCOPE_CHANNEL_MANAGE_VIPS,
	TWITCH_SCOPE_CHANNEL_MANAGE_GUEST_STAR,
	TWITCH_SCOPE_CHANNEL_MANAGE_MODERATORS,
	TWITCH_SCOPE_CHANNEL_MODERATE,
	TWITCH_SCOPE_CHANNEL_READ_EDITORS,
	TWITCH_SCOPE_CHANNEL_READ_GOALS,
	TWITCH_SCOPE_CHANNEL_READ_HYPE_TRAIN,
	TWITCH_SCOPE_CHANNEL_READ_POLLS,
	TWITCH_SCOPE_CHANNEL_READ_PREDICTIONS,
	TWITCH_SCOPE_CHANNEL_READ_REDEMPTIONS,
	TWITCH_SCOPE_CHANNEL_READ_STREAM_KEY,
	TWITCH_SCOPE_CHANNEL_READ_SUBSCRIPTIONS,
	TWITCH_SCOPE_CHANNEL_READ_ADS,
	TWITCH_SCOPE_CHANNEL_READ_VIPS,
	TWITCH_SCOPE_CHANNEL_READ_CHARITY,
]

var _scopes_chat = [
	TWITCH_SCOPE_CHAT_EDIT,
	TWITCH_SCOPE_CHAT_READ,
]

var _scopes_clips = [
	TWITCH_SCOPE_CLIPS_EDIT,
]

var _scopes_moderation = [
	TWITCH_SCOPE_MODERATION_READ,
	TWITCH_SCOPE_MODERATOR_READ_BLOCKED_TERMS,
	TWITCH_SCOPE_MODERATOR_READ_CHAT_MESSAGES,
	TWITCH_SCOPE_MODERATOR_READ_CHAT_SETTINGS,
	TWITCH_SCOPE_MODERATOR_READ_FOLLOWERS,
	TWITCH_SCOPE_MODERATOR_READ_CHATTERS,
	TWITCH_SCOPE_MODERATOR_READ_UNBAN_REQUESTS,
	TWITCH_SCOPE_MODERATOR_READ_GUEST_STAR,
	TWITCH_SCOPE_MODERATOR_READ_SHIELD_MODE,
	TWITCH_SCOPE_MODERATOR_READ_AUTOMOD_SETTINGS,
	TWITCH_SCOPE_MODERATOR_MANAGE_AUTOMOD,
	TWITCH_SCOPE_MODERATOR_MANAGE_AUTOMOD_SETTINGS,
	TWITCH_SCOPE_MODERATOR_MANAGE_BANNED_USERS,
	TWITCH_SCOPE_MODERATOR_MANAGE_BLOCKED_TERMS,
	TWITCH_SCOPE_MODERATOR_MANAGE_CHAT_SETTINGS,
	TWITCH_SCOPE_MODERATOR_MANAGE_CHAT_MESSAGES,
	TWITCH_SCOPE_MODERATOR_MANAGE_UNBAN_REQUESTS,
	TWITCH_SCOPE_MODERATOR_MANAGE_GUEST_STAR,
	TWITCH_SCOPE_MODERATOR_MANAGE_SHIELD_MODE,
	TWITCH_SCOPE_MODERATOR_MANAGE_SHOUTOUTS,
	TWITCH_SCOPE_MODERATOR_MANAGE_ANNOUNCEMENTS,
	TWITCH_SCOPE_MODERATOR_MANAGE_WARNINGS,
]

var _scopes_user = [
	TWITCH_SCOPE_USER_BOT,
	TWITCH_SCOPE_USER_EDIT,
	TWITCH_SCOPE_USER_EDIT_BROADCAST,
	TWITCH_SCOPE_USER_MANAGE_BLOCKED_USERS,
	TWITCH_SCOPE_USER_MANAGE_CHAT_COLOR,
	TWITCH_SCOPE_USER_MANAGE_WHISPERS,
	TWITCH_SCOPE_USER_READ_BLOCKED_USERS,
	TWITCH_SCOPE_USER_READ_BROADCAST,
	TWITCH_SCOPE_USER_READ_EMAIL,
	TWITCH_SCOPE_USER_READ_SUBSCRIPTIONS,
	TWITCH_SCOPE_USER_READ_EMOTES,
	TWITCH_SCOPE_USER_READ_FOLLOWS,
	TWITCH_SCOPE_USER_READ_MODERATED_CHANNELS,
	TWITCH_SCOPE_USER_WRITE_CHAT,
	TWITCH_SCOPE_USER_READ_CHAT,
]

var _scopes_whispers = [
	TWITCH_SCOPE_WHISPERS_READ,
	TWITCH_SCOPE_WHISPERS_EDIT
]


///////////////////////////////////////////////////////////////////

show_debug_message("------Adding Scopes------");
with(obj_twitch_scope)
{
	show_debug_message($"{text} : {!locked ? "YES" : "NO"}");
	if (!locked)
	switch(text)
	{
		case "Analytics": _scopes = array_concat(_scopes, _scopes_analytics); break;
		case "Bits": _scopes = array_concat(_scopes, _scopes_bits); break;
		case "Channel": _scopes = array_concat(_scopes, _scopes_channel); break;
		case "Chat": _scopes = array_concat(_scopes, _scopes_chat); break;
		case "Clips": _scopes = array_concat(_scopes, _scopes_clips); break;
		case "Moderation": _scopes = array_concat(_scopes, _scopes_moderation); break;
		case "User": _scopes = array_concat(_scopes, _scopes_user); break;
		case "Whispers": _scopes = array_concat(_scopes, _scopes_whispers); break;
	}
}
show_debug_message("-------------------------");

twitch_auth(_scopes,,,
			function(_data)
			{
				room_goto(rm_twitch_menu_1)
			},
			function()
			{
				show_message_async("twitch_auth FAILED")
			}
		)
