name: Bug Report
description: File a bug report for issues that only happen when this extension is in your project
labels: ["Twitch"]
type: "Extension Bug"
body:
  - type: markdown
    attributes:
      value: |
        For any GameMaker Account or licencing issues (including "I can't see all my platforms in Target Manager") please submit a [Helpdesk Ticket](https://contact.gamemaker.io/contact-us#account) instead of using this form.
        
        Please also ensure you have searched for any existing reports of this issue before you begin - if one exists, please leave a thumbs-up on that one, rather than knowingly filing a duplicate report, as duplicates just slow things down.
       
        Note that most fields are required to be filled-in before you can submit this report, as it is all essential information which we will require in order to confirm and fix your issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write a concise yet detailed description of the issue and do include any relevant screenshots at suitable locations in the body of your text. Please do not copy/paste lots of code in this field - attach a sample project instead, as requested below. (Also, do not add a web link as your entire bug report and assume we will read the external thread to work it out ourselves, as we will most likely simply close the report!)
    validations:
      required: true
      
  - type: input
    id: expected
    attributes:
      label: Expected Change
      description: If it is not obvious from your Description text, what difference would you expect to see once this is fixed?
    validations:
      required: false
      
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Add the detailed, ordered steps for someone else to reproduce the issue into the gaps below (add as many steps into the middle as you require)
      value: |
        1. Start GameMaker
        2. 
        3. 
        4. See the issue
    validations:
      required: true
      
  - type: dropdown
    id: repro-rate
    attributes:
      label: How reliably can you recreate this issue using your steps above?
      options:
        - Always
        - Most Times
        - Only Sometimes
        - Rarely
        - Only Ever Happened Once 
    validations:
      required: true
      
  - type: dropdown
    id: version
    attributes:
      label: Which version of GameMaker are you reporting this issue for?
      description: Please put the exact version number in your Description (If your version is older and therefore not in this list, please update and confirm your issue is not already fixed before you send any report!)
      multiple: true
      options:
        - Monthly
        - LTS
        - Beta
        - Other Release
    validations:
      required: true
      
  - type: dropdown
    id: platforms
    attributes:
      label: Which platform(s) are you seeing the problem on?
      multiple: true
      options: 
        - Windows
        - macOS
        - Ubuntu
        - Android
        - iOS
        - tvOS
        - HTML5
        - GX.games
        - PlayStation 4
        - PlayStation 5
        - Switch
        - Xbox (GDK)
    validations:
      required: false
      
  - type: input
    id: sample
    attributes:
      label: Sample Package
      description: Please create as small a sample project as you can make which shows the problem and then use the Help > Upload a Bug Package tool inside GameMaker. Say yes to including that little sample project! Then paste the download URL into the box below.
    validations:
      required: false
          
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
